In [22]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn import linear_model

In [23]:
df = pd.read_csv("dataset.csv")
df.head()

,Complaint_ID,Complaint_Text,Category,Priority,Language,Source,Resolution_Time_Hours
0,1,High noise levels in Bus Stand disturbing resi...,Noise Pollution,Low,english,synthetic,85
1,2,High noise levels in Highway Stretch disturbin...,Noise Pollution,High,english,synthetic,9
2,3,Water leakage observed near Residential Colony...,Water Leakage,High,english,synthetic,31
3,4,Water leakage observed near Main Road affectin...,Water Leakage,Medium,english,synthetic,39
4,5,Garbage not collected in Hospital Road for sev...,Garbage Collection,Low,english,synthetic,76

In [24]:
priority_map = {"Low":1,"Medium":2,"High":3}
df["Priority"] = df["Priority"].map(priority_map)
df.head()

,Complaint_ID,Complaint_Text,Category,Priority,Language,Source,Resolution_Time_Hours
0,1,High noise levels in Bus Stand disturbing resi...,Noise Pollution,1,english,synthetic,85
1,2,High noise levels in Highway Stretch disturbin...,Noise Pollution,3,english,synthetic,9
2,3,Water leakage observed near Residential Colony...,Water Leakage,3,english,synthetic,31
3,4,Water leakage observed near Main Road affectin...,Water Leakage,2,english,synthetic,39
4,5,Garbage not collected in Hospital Road for sev...,Garbage Collection,1,english,synthetic,76

In [25]:
dummies = pd.get_dummies(df["Category"])
dummies.head()

,Drainage Blockage,Garbage Collection,Noise Pollution,Road Damage,Streetlight Failure,Water Leakage
0,False,False,True,False,False,False
1,False,False,True,False,False,False
2,False,False,False,False,False,True
3,False,False,False,False,False,True
4,False,True,False,False,False,False

In [26]:
merged = pd.concat([df,dummies],axis="columns")
merged.head()

,Complaint_ID,Complaint_Text,Category,Priority,Language,Source,Resolution_Time_Hours,Drainage Blockage,Garbage Collection,Noise Pollution,Road Damage,Streetlight Failure,Water Leakage
0,1,High noise levels in Bus Stand disturbing resi...,Noise Pollution,1,english,synthetic,85,False,False,True,False,False,False
1,2,High noise levels in Highway Stretch disturbin...,Noise Pollution,3,english,synthetic,9,False,False,True,False,False,False
2,3,Water leakage observed near Residential Colony...,Water Leakage,3,english,synthetic,31,False,False,False,False,False,True
3,4,Water leakage observed near Main Road affectin...,Water Leakage,2,english,synthetic,39,False,False,False,False,False,True
4,5,Garbage not collected in Hospital Road for sev...,Garbage Collection,1,english,synthetic,76,False,True,False,False,False,False

In [27]:
final = merged.drop(columns=["Category"])
final.head()

,Complaint_ID,Complaint_Text,Priority,Language,Source,Resolution_Time_Hours,Drainage Blockage,Garbage Collection,Noise Pollution,Road Damage,Streetlight Failure,Water Leakage
0,1,High noise levels in Bus Stand disturbing resi...,1,english,synthetic,85,False,False,True,False,False,False
1,2,High noise levels in Highway Stretch disturbin...,3,english,synthetic,9,False,False,True,False,False,False
2,3,Water leakage observed near Residential Colony...,3,english,synthetic,31,False,False,False,False,False,True
3,4,Water leakage observed near Main Road affectin...,2,english,synthetic,39,False,False,False,False,False,True
4,5,Garbage not collected in Hospital Road for sev...,1,english,synthetic,76,False,True,False,False,False,False

In [28]:
x = final.drop(columns=["Complaint_ID","Complaint_Text","Language","Source","Resolution_Time_Hours"])
x.head()

,Priority,Drainage Blockage,Garbage Collection,Noise Pollution,Road Damage,Streetlight Failure,Water Leakage
0,1,False,False,True,False,False,False
1,3,False,False,True,False,False,False
2,3,False,False,False,False,False,True
3,2,False,False,False,False,False,True
4,1,False,True,False,False,False,False

In [29]:
y = final.Resolution_Time_Hours
y.head()

0    85
1     9
2    31
3    39
4    76
Name: Resolution_Time_Hours, dtype: int64

In [30]:
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression()

In [31]:
reg.predict(x)

array([95.81202486, 14.18724839, 14.17580708, ..., 55.21244315,
       95.81202486, 54.98819531])

In [32]:
reg.score(x,y)

0.862687263471586

In [34]:
import pickle

In [35]:
with open("model_pickle",'wb') as file:
  pickle.dump(reg,file)

In [36]:
with open("model_pickle",'rb') as file:
  model=pickle.load(file)

In [37]:
model.coef_

array([-40.81238823,  -0.4160566 ,   0.50722841,  -0.62886312,
         0.23805532,   0.93994042,  -0.64030443])

In [38]:
model.intercept_

np.float64(137.2532762102271)

In [39]:
model.predict(x)

array([95.81202486, 14.18724839, 14.17580708, ..., 55.21244315,
       95.81202486, 54.98819531])

In [40]:
import joblib

In [41]:
joblib.dump(reg,"model_job")

['model_job']

In [42]:
mj = joblib.load("model_job")

In [43]:
mj.coef_

array([-40.81238823,  -0.4160566 ,   0.50722841,  -0.62886312,
         0.23805532,   0.93994042,  -0.64030443])