In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("dataset.csv")
df.head()

   Complaint_ID  ... Resolution_Time_Hours
0             1  ...                    85
1             2  ...                     9
2             3  ...                    31
3             4  ...                    39
4             5  ...                    76

[5 rows x 7 columns]

In [6]:
priority_map = {"Low":1,"Medium":2,"High":3}
df["Priority"]=df['Priority'].map(priority_map)

df.head()

   Complaint_ID  ... priority
0             1  ...        1
1             2  ...        3
2             3  ...        3
3             4  ...        2
4             5  ...        1

[5 rows x 8 columns]

In [7]:
x = df['Priority']
y = df['Resolution_Time_Hours']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [10]:
x_test

1572    1
1668    3
1797    2
1243    1
324     3
       ..
175     2
1639    3
936     1
1728    1
1540    3
Name: Priority, Length: 600, dtype: int64

In [11]:
y_test

1572     82
1668     19
1797     66
1243    116
324       3
       ...
175      40
1639     22
936      98
1728     95
1540     15
Name: Resolution_Time_Hours, Length: 600, dtype: int64